name: "autotask_client"
services:
  appserver:
    type: php:8.3
tooling:
  php:
    service: appserver
  phpunit:
    service: appserver
  autotask:
    service: appserver
    cmd: /app/vendor/anteris-dev/autotask-client-generator/bin/autotask
  composer:
    service: appserver
